### ISSUE TITLE
Make tag selector more useful

### ISSUE THREAD

**Issue by jordij** [springload/madewithwagtail#19]

**Comment by bwjwright** [comment]
This one probably doesn't need to be too crazy, the main issue is too many tags showing on the homepage. 

What we could do is reduce the number of tags showing when the page loads to something more manageable like 8 – 10? Either so it shows as roughly one line when you're on a desktop and so that it's not too overwhelming on mobile. Then we add a little link to show more tags which loads in the rest of the tags like so:

![tags 1](https://cloud.githubusercontent.com/assets/11985283/14837055/522d1946-0c69-11e6-9283-116e48d75943.png)

Then we could have another link to show fewer tags on the page which removes all the rest of the tags.

![tags 2](https://cloud.githubusercontent.com/assets/11985283/14837084/899334ec-0c69-11e6-81d2-452e76ff3b74.png)

Another idea was to just randomly load 8 – 10 tags each time the page loads. Maybe this is just over complicated but it might be a nice way to mix it up and let people find things they weren't expecting to see. You could even have a text link to 'Show more tags' which loads in another random set of 8 – 10 tags so the user doesn't have to reload the page.

Anyway, theres 2 ideas. Anyone have any thoughts?

**Comment by jordij** [comment]
Yeah this looks it'll help Ben.
