### ISSUE TITLE
Form submissions ordering is broken

### ISSUE THREAD

**Issue by thibaudcolas** [springload/madewithwagtail#48]
I think this has started happening when I removed a bunch of spammy submissions on the site. I thought submissions were ordered by date, from oldest to newest, but now new submissions are positioned in a seemingly erratic manner in-between old ones.

This affects both the table at http://madewithwagtail.org/admin/forms/submissions/5/ and the CSV export.

Here's the weird order on a subset of the submissions (the CSV provides a fuller picture):

<img width="212" alt="madewithwagtail-submissions-order" src="https://cloud.githubusercontent.com/assets/877585/20189876/aebee392-a787-11e6-948f-332533278994.png">

Ideally we would want to display all submissions from most recent to oldest I think.

**Comment by loicteixeira** [comment]
This [commit](https://github.com/torchbox/wagtail/commit/4edcb61c6a9b89659b5b12d37ef768116b25c120) on `wagtail.wagtailforms` does that and has landed in Wagtail 1.7. Opening a seperate issue to upgrade Wagtail.

**Comment by loicteixeira** [comment]
So #65 upgrade Wagtail to 1.9 which has the fix for ordering of the submissions, only it actually order them in ascending order (i.e. new submissions are on the last page) which is not ideal but at least it's in order.

I can't think of an easy way to order this in descending order. I'm willing to consider and discuss the idea of `Login for developers` express in #38 which might make this irrelevant? So I'm happy to close this issue. Thoughts?

**Comment by thibaudcolas** [comment]
👍  latest first would be best but as far as this issue goes any ordering is good. Closing.
