### ISSUE TITLE
Differentiation needed on form for submissions from a company vs individual dev

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#79]
There have been a few Made with Wagtail submissions that have come through as single dev work due to the field labels but have actually been on behalf of teams.

To make sure we're getting the right name and description info I think the relevant field labels should be updated to "Company/Developer Name", "Company/Developer description" etc to cover both scenarios.

**Comment by jennyadamsnz** [comment]
What are your thoughts on this one Thibaud?

**Comment by thibaudcolas** [comment]
Hey @jennyadamsnz, I understand the problem statement but I'm not about the solution. We chose to call those profiles "Developer" on purpose because it would address the fact that sites can be made by individuals, teams, and all sorts of organisations.

Perhaps we could replace all occurences of "Developer" with "Profile" on the form, to make it clear that this information will end up on their public profile?

I think another option would be to add radio buttons before "Contact email" that state:

> This site was built by
> [ ] Myself [ ] My organisation

What do you think? Overkill?

**Comment by jennyadamsnz** [comment]
I like both options and I've applied them to the saved draft for you to review but I'd also like to advocate for "My Team" instead of "My organisation" because I think this is a clearer and more inclusive term but please let me know if you don't agree.  http://madewithwagtail.org/admin/pages/5/view_draft/

**Comment by jennyadamsnz** [comment]
Please note- I've used a drop-down menu for this "This site was built by:" field instead of radio buttons as these require a bunch of extra styling to get them inline and without bullet points etc... see what you think.

**Comment by thibaudcolas** [comment]
Dropdown look good, but I still think "My organisation" would be a better label (and also note it's Sentence case, not Title Case).

The reason is that people often submit sites they haven't contributed to themselves, or have been built by more than one team. "Organisation" is more vague, and closer to the type of profiles we are after. This also happens to be the terminology lots of products use – GitHub, Trello, Zeplin, etc.

**Comment by jennyadamsnz** [comment]
OK, that's good to know. I have updated that on the saved draft.
