### ISSUE TITLE
Ability to re-arrange sites within a Developer profile

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#80]
Andy from Rock Kitchen Harris has enquired re having the option to be able to re-arrange their website submissions on their Developer profile page either alphabetically or in a custom order so they can feature their best work first (current pushed on to the second page as the order is currently chronological and their major projects were submitted first). This is currently possible with the featured tick box but this would also impact the home page featured items. Ideally it would be great to have a home page featured option and a seperate featured option within the individual developer profiles.

**Comment by thibaudcolas** [comment]
Makes perfect sense to me. I'm not sure how best to implement this, suggestions welcome!

**Comment by loicteixeira** [comment]
Sorry I wasn't watching this repo for some reason..

[Children](https://github.com/springload/madewithwagtail/blob/c7ba7f8b16186ccf5c6c28484758df2c07eab861/core/models.py#L313-L314) need to be ordered by `path` (or `-path` I can never remember) instead of `-first_published_at`.

But maybe it would make sense to have an option on the page to allow either alphabetical or manual ordering, e.g. `WagtailCompanyPage` could have:

```python
# At the top of the file
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

# In the class
automatic_ordering_of_sites = models.BooleanField(
    default=True,
    help_text=mark(
        _(
            'Whether the sites are automatically listed in alphabetical order '
            'or <a href="{}" target="_blank">manually ordered</a> through the admin.'
        ).format('http://docs.wagtail.io/en/v1.8/editor_manual/finding_your_way_around/the_explorer_page.html#reordering-pages')
    )

    def children(self):
        qs = WagtailSitePage.objects.live().descendant_of(self)
        if self.automatic_ordering_of_sites:
            qs = qs.order_by('title')
        else:
            qs = qs.order_by('path')  # or `-path`?
        return

    # TODO: Update the panels
```

I'll try to make a PR if you agree with the process.

Note:
- `path` should be the default ordering so just removing the existing `order_by` should do (to be tested though).
- ordering by `first_publish_at` is more or less useless because it essentially does the same thing as ordering by `path` because when you create a new page, it will have a path which comes after all the previous pages path. So adding a `-` to the ordering to reverse it makes sense, but using `first_publish_at` just waste the manual ordering of the admin.

**Comment by jennyadamsnz** [comment]
Sounds good! Let's do it!
