### ISSUE TITLE
Required fields unclear

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#84]
It's unclear which fields are required or optional. This is mentioned in a note in the "Profile description" field but this could be easily missed. I think it's good for there to be clarity here especially for regular submitters.

**Comment by jennyadamsnz** [comment]
I have added a "*" to the required fields which I believe is common practice for indicating required fields in forms. Thibaud please let me know what you think.  Please note- This change has been applied to a saved draft only, not the live form.

**Comment by thibaudcolas** [comment]
👍 nice! If there is an asterisk, there should be a label somewhere on the form that states "* Required field". Please try and add it if that's not too complicated.

**Comment by jennyadamsnz** [comment]
[export (9).pdf](https://github.com/springload/madewithwagtail/files/1189489/export.9.pdf)
test was successful

**Comment by jennyadamsnz** [comment]
I have also added "(*) Indicates a required field" to the start of the form http://madewithwagtail.org/admin/pages/5/view_draft/

**Comment by thibaudcolas** [comment]
I understand that it would work with new submissions, but what happens of old ones that were made with different field names? It's a big price to pay to lose all of that history just for some label changes.

**Comment by loicteixeira** [comment]
Since the fields are marked as required in the admin, the template should be able to pick it up and add a `required` class to the field like we do on all other projects. If the basic [form.as_p](https://github.com/springload/madewithwagtail/blob/c7ba7f8b16186ccf5c6c28484758df2c07eab861/core/templates/core/submit_form_page.html#L17) doesn't do it, we will have to loop over the fields and do it ourselves.

**Comment by loicteixeira** [comment]
To my surprise, adding an asterisk to the label doesn't break the CSV Export. This is because it uses [clean_name](https://github.com/wagtail/wagtail/blob/aeef5a54541640988eb319fab3331088e57d080a/wagtail/wagtailforms/models.py#L102-L107) when saving to the database and exporting to the CSv.

However, note that the CSV Export has been "broken" on July 31st (see #98).

Anyway, as expressed before, I strongly believe this change should be a code change, not a hack in the admin. The above PR addresses that and I'll remove the `*` from the label once the PR is merged and deployed.

**Comment by loicteixeira** [comment]
I've deployed the code and while the CSS change is apparent (the new class exists), the form don't get the class applied.
